(() => {
  const polish = location.pathname.includes('/pl/');
  const gamePage = location.pathname.includes('kebab-shooter');
  const englishTarget = gamePage ? (polish ? '../kebab-shooter.html' : 'kebab-shooter.html') : (polish ? '../index.html' : 'index.html');
  const polishTarget = gamePage ? (polish ? 'kebab-shooter.html' : 'pl/kebab-shooter.html') : (polish ? 'index.html' : 'pl/index.html');
  const labels = document.createElement('div'); labels.className = 'language-switch';
  labels.innerHTML = polish ? `<a href="${englishTarget}">🇬🇧 EN</a><strong>🇵🇱 PL</strong>` : `<strong>🇬🇧 EN</strong><a href="${polishTarget}">🇵🇱 PL</a>`;
  document.querySelector('.site-header')?.append(labels);
  if (!polish && localStorage.getItem('mareek-language') === 'pl') location.href = 'pl/index.html';
  if (!polish && !localStorage.getItem('mareek-language') && navigator.language.toLowerCase().startsWith('pl')) { localStorage.setItem('mareek-language', 'pl'); location.href = 'pl/index.html'; }
  labels.addEventListener('click', (event) => { const link = event.target.closest('a'); if (link) localStorage.setItem('mareek-language', link.href.includes('/pl/') ? 'pl' : 'en'); });
  if (!polish) return;
  const t = {
    'Focus':'Tematyka','Videos':'Filmy','Contact':'Kontakt','Back to home':'Powrót','Explore the channel':'Przejdź do kanału','Watch selected videos':'Oglądaj wybrane filmy','Ultrawide Gaming':'Gaming Ultrawide','Performance Tests':'Testy wydajności','Indie Game Dev':'Tworzenie gier indie','Enter the kitchen ↗':'Poznaj grę ↗','Selected videos.':'Wybrane filmy.','Selected shorts.':'Wybrane shorty.','Start a conversation ↗':'Napisz do mnie ↗',
    'GAMING • ULTRAWIDE • PERFORMANCE • INDIE DEV':'GAMING • ULTRAWIDE • PERFORMANCE • INDIE DEV','THE MAREEKPLAYS FORMULA':'FORMUŁA MAREEKPLAYS','One channel.':'Jeden kanał.','Three ways to play.':'Trzy sposoby grania.','Discover ↗':'Odkryj ↗','See the tests ↗':'Zobacz testy ↗','Building Kebab Shooter from the first prototype to Steam Deck.':'Tworzę Kebab Shooter — od pierwszego prototypu po Steam Deck.','MAREEKPLAYS ORIGINAL':'ORYGINALNY PROJEKT MAREEKPLAYS','Meet ':'Poznaj ','A fast, weird and wonderfully snackable 2D shooter in development. Follow the journey from desktop to Steam Deck.':'Szybka, nietypowa i pełna kebabowego humoru strzelanka 2D. Śledź jej drogę od prototypu po kolejne wersje.','Explore the game ↗':'Poznaj grę ↗','FROM THE CHANNEL':'Z KANAŁU','View all on YouTube ↗':'Zobacz wszystko na YouTube ↗','Early Steam Deck gameplay.':'Wczesny gameplay na Steam Deck.','Cinematic world &amp; gameplay — ultrawide.':'Filmowy świat i gameplay — ultrawide.','Fatekeeper — ultrawide RTX 4080 test.':'Fatekeeper — test ultrawide na RTX 4080.','QUICK LOOKS':'SZYBKIE UJĘCIA','View all Shorts ↗':'Zobacz wszystkie Shortsy ↗','Stay in the':'Bądź na bieżąco.','loop.':'z nami.','FOLLOW THE SIGNAL':'OBSERWUJ MAREEKPLAYS','Got a game':'Masz grę','to share?':'do pokazania?','CONTACT &amp; COLLABORATIONS':'KONTAKT I WSPÓŁPRACA','Gaming beyond the frame.':'Gaming poza kadrem.','For game keys, review opportunities and selected collaborations, get in touch at':'W sprawie kluczy do gier, recenzji i współpracy napisz na','Some games may be provided through platforms such as Keymailer. Games received this way are marked with a hashtag, and receiving a key does not influence the coverage or opinion presented.':'Niektóre gry mogą być przekazywane przez platformy takie jak Keymailer. Materiały otrzymane w ten sposób oznaczam hashtagiem, a otrzymanie klucza nie wpływa na moją opinię ani sposób prezentacji gry.',
    'MAREEKPLAYS ORIGINAL • ANDROID • EARLY BUILD':'ORYGINALNY PROJEKT MAREEKPLAYS • ANDROID • WCZESNY BUILD','A fast, colourful 2D action game about kebabs, delivery vans and surviving the chaos — now being tested on Android.':'Kolorowa gra akcji 2D o kebabach, latających dostawczakach i przetrwaniu w chaosie — obecnie testowana na Androidzie.','Watch gameplay ↗':'Zobacz gameplay ↗','THE IDEA':'POMYSŁ','Small game.':'Mała gra.','Big flavour.':'Wielki smak.','Kebab Shooter is a 2D indie game currently in development by MareekPlays. It mixes arcade action, a playful food-truck world and a distinctly homemade sense of humour.':'Kebab Shooter to niezależna gra 2D tworzona przez MareekPlays. Łączy zręcznościową akcję, świat food trucków i charakterystyczne poczucie humoru.','The first planned platform is Android. The current build is being tested on mobile devices, with gameplay, controls and balance still evolving.':'Pierwszą planowaną platformą jest Android. Obecny build jest testowany na urządzeniach mobilnych, a gameplay, sterowanie i balans nadal się zmieniają.','ANDROID TEST BUILD':'TESTOWY BUILD NA ANDROIDZIE','See the ':'Zobacz ','world.':'świat.','ROAD AHEAD':'CO DALEJ','Coming':'Następne','next.':'etapy.','Android early-build testing':'Testy wczesnego buildu na Androidzie','Gameplay and controls refinement':'Dopracowanie gameplayu i sterowania','Future platform plans':'Plany dotyczące kolejnych platform','Android is planned as the first platform. Release timing and additional platforms will be announced as development progresses.':'Android jest pierwszą planowaną platformą. Termin premiery i kolejne platformy zostaną ogłoszone wraz z postępem prac.'
  };
  document.querySelectorAll('h1,h2,h3,p,a,span,b').forEach((el) => { const key = el.innerHTML.trim(); if (t[key]) el.innerHTML = t[key]; });
  document.documentElement.lang = 'pl';
})();
